apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodewatcher-v1.5
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name:  nodewatcher-v1.5
    app:  nodewatcher-v1.5
spec:
  selector:
    matchLabels:
      app:  nodewatcher-v1.5
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        stage: staging
        name:  nodewatcher-v1.5
        app:  nodewatcher-v1.5
    spec:
      containers:
        - name: prisma
          image: prismagraphql/prisma:1.34
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: prisma-config
                  key: prisma-config
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials-v1.5
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials-v1.5
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials-v1.5
                  key: dbname
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: ["/cloud_sql_proxy",
          "--dir=/cloudsql",
          "-instances=test-installations-222013:europe-west1:kusama-etl=tcp:0.0.0.0:5432",
          "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials