apiVersion: v1
kind: Service
metadata:
  name: nodewatcher-v1-5
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nodewatcher-v1.5
    app: nodewatcher-v1.5
spec:
  type: ClusterIP
  selector:
    app: nodewatcher-v1.5
  ports:
    - protocol: TCP
      port: 4466
      targetPort: 4466