apiVersion: batch/v1
kind: Job
metadata:
  name: nomidotwatcher-v1.5
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nomidotwatcher-v1.5
    app: nomidotwatcher-v1.5
    job-name: nomidotwatcher-v1.5
spec:
  manualSelector: true
  selector:
    matchLabels:
      stage: staging
      name: nomidotwatcher-v1.5
      app: nomidotwatcher-v1.5
      job-name: nomidotwatcher-v1.5
  template:
    metadata:
      labels:
        stage: staging
        name: nomidotwatcher-v1.5
        app: nomidotwatcher-v1.5
        job-name: nomidotwatcher-v1.5
    spec:
      restartPolicy: Never
      containers:
        - name: nomidotwatcher
          image: eu.gcr.io/test-installations-222013/nomidot_watcher@sha256:1dc353d48e0d0db6140a840102ba6f63f083677bc5045e45cc61129391da1eb6
          imagePullPolicy: Always
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
            - name: START_FROM
              value: '0'
            - name: BLOCK_IDENTIFIER
              value: 'job-v1.5'
            - name: MAX_LAG
              value: '10'
          command: ["yarn", "start"]