apiVersion: v1
kind: Service
metadata:
  name: nodewatcher
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nodewatcher
    app: nodewatcher
spec:
  type: LoadBalancer
  selector:
    app: nodewatcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080