apiVersion: v1
kind: Service
metadata:
  name: nodewatcher
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nodewatcher
    app: nodewatcher
spec:
  type: NodePort
  selector:
    app: nodewatcher
  ports:
    - protocol: TCP
      port: 4466
      targetPort: 4466
      nodePort: 31000