apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomidot-frontend
  namespace: nomidot-frontend-staging
spec:
  selector:
    matchLabels:
      app: nomidot-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: nomidot-frontend
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nomidot-frontend
        image: eu.gcr.io/test-installations-222013/nomidot-frontend@sha256:24030800773012141b792f20a30c4c60e3d5b40f58f97fee14b9612249e78c9f
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]