apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: nomidot-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: nomidot-frontend
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nomidot-frontend
        image: eu.gcr.io/test-installations-222013/nomidot-frontend@sha256:6487140db97b98f4c95e5ef32166782ca40e1243d2ca66d6dabe309068f4088b
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]