apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: main
  name: main
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: main
    spec:
      containers:
      - image: eu.gcr.io/kusama-etl-261513/node_watcher_main@sha256:ac2aaa5658540579a26c92ec64862fdf8574b2e87dfe5685743052a8c7d7a30d
        name: main
        resources: {}
      restartPolicy: Always
status: {}
