projects:
    app:
        schemPath: src/schema.graphql
        extensions:
            endpoints:
            default: http://localhost:4000
    prisma:
        schemaPath: ../node_watcher/src/generated/prisma_client/prisma-schema.ts
        extensions:
            prisma: ../node_watcher/prisma.yml