projects:
  app:
    schemPath: src/schema.graphql
    extensions:
    endpoints:
    default: http://0.0.0.0:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
    prisma: prisma/prisma.yml