apiVersion: batch/v1
kind: Job
metadata:
  name: nomidotwatcher-last-50k
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nomidotwatcher
    app: nomidotwatcher
    job-name: nomidotwatcher-last-50k
spec:
  manualSelector: true
  selector:
    matchLabels:
      stage: staging
      name: nomidotwatcher
      app: nomidotwatcher
      job-name: nomidotwatcher-last-50k
  template:
    metadata:
      labels:
        stage: staging
        name: nomidotwatcher
        app: nomidotwatcher
        job-name: nomidotwatcher-last-50k
    spec:
      restartPolicy: Never
      containers:
        - name: nomidotwatcher
          image: eu.gcr.io/test-installations-222013/nomidot_watcher@sha256:d10c9c30694f35e7e88bcd910441788810dad289454555da771485d5fa81a40e
          imagePullPolicy: Always
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
            - name: START_FROM
              value: '1305897'
            - name: BLOCK_IDENTIFIER
              value: 'last-50k-1'
            - name: MAX_LAG
              value: '10'
          command: ["yarn", "start"]
