apiVersion: batch/v1
kind: Job
metadata:
  name: nomidotwatcher-last-50k
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nomidotwatcher
    app: nomidotwatcher
    job-name: nomidotwatcher-last-50k
spec:
  manualSelector: true
  selector:
    matchLabels:
      stage: staging
      name: nomidotwatcher
      app: nomidotwatcher
      job-name: nomidotwatcher-last-50k
  template:
    metadata:
      labels:
        stage: staging
        name: nomidotwatcher
        app: nomidotwatcher
        job-name: nomidotwatcher-last-50k
    spec:
      restartPolicy: Never
      containers:
        - name: nomidotwatcher
          image: eu.gcr.io/test-installations-222013/nomidot_watcher@sha256:12a1ab7eb7138068b6a562cd0d386f64d50b55bd883643e00d1e569b1e08985c
          imagePullPolicy: Always
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
            - name: START_FROM
              value: '1177733'
            - name: BLOCK_IDENTIFIER
              value: 'last-50k'
          command: ["yarn", "start"]
