apiVersion: batch/v1
kind: Job
metadata:
  name: nomidotwatcher-160366
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nomidotwatcher
    app: nomidotwatcher
    job-name: nomidotwatcher-160366
spec:
  manualSelector: true
  selector:
    matchLabels:
      stage: staging
      name: nomidotwatcher
      app: nomidotwatcher
      job-name: nomidotwatcher-160366
  template:
    metadata:
      labels:
        stage: staging
        name: nomidotwatcher
        app: nomidotwatcher
        job-name: nomidotwatcher-160366
    spec:
      restartPolicy: Never
      containers:
        - name: nomidotwatcher
          image: eu.gcr.io/test-installations-222013/nomidot_watcher@sha256:815a78318b769ba830b872947052e47daa1f25179cc29bfa246ef79d82542be5
          imagePullPolicy: Always
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
            - name: START_FROM
              value: '160366'
          command: ["yarn", "start"]